sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
      -
        handle: description
        field: bard.description
        config:
          buttons:
            - h3
            - bold
            - italic
            - unorderedlist
            - orderedlist
            - removeformat
            - anchor
      -
        handle: sections
        field: replicator.sections
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          localizable: true
      -
        handle: icon
        field: assets.icon
      -
        handle: image
        field: assets.image
title: Products
